### ISSUE TITLE
Can we move the statistics calculations to a separate management command?

### ISSUE THREAD

**Issue by sahilchinoy** [rskwan/ucb-grade-dists#3]
I think recomputing statistics every time we call `save` is slowing down the import process. Might be easier to compute those manually via a management command? Thoughts?

**Comment by sahilchinoy** [comment]
Calculate macro statistics for each division (undergrad, grad). Not sure where the best place to store this in the database would be, but it would enable us to compare subjects to Berkeley-wide trends.

**Comment by rskwan** [comment]
I've moved the stats computations to their own functions rather than save, and added appropriate calls in the management commands. (as of commit d5ed529a8de25e1d2388ea916b5c02afe8406e22) I haven't done computations into divisions yet, though.
